### ISSUE TITLE
DEV - Pull request size validation

### ISSUE THREAD

**Issue by cgbosse** [Nautilus-Cyberneering/chinese-ideographs#18]
POC - REL 02 - 
Developers (on behalf of artists) can only upload one image at a time. But they can upload the json or tiff image independently

**Comment by josecelano** [comment]
I think the intention for this issue was to check if the PR for a new GOld image only contains one image. Either if you are adding a new one or updating or deleting a previous one. I'm going to change the milestone for this issue as I think we have to review to whole backlog after finishing the POC01.
